apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-debmirror-cron-ubuntu-ports
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: local-packages
            persistentVolumeClaim:
              claimName: packages-ubuntu-ports
          containers:
          - name: ubuntu-ports
            image: iainlane/debmirror-ubuntu
            envFrom:
            - configMapRef:
                name: debmirror-ubuntu-ports-conf
            imagePullPolicy: Always
            volumeMounts:
            - name: local-packages
              mountPath: "/mirror"
          restartPolicy: OnFailure
          priorityClassName: debmirror-high-priority
  concurrencyPolicy: Forbid
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-debmirror-cron-ubuntu
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: local-packages
            persistentVolumeClaim:
              claimName: packages-ubuntu
          containers:
          - name: ubuntu
            image: iainlane/debmirror-ubuntu
            envFrom:
            - configMapRef:
                name: debmirror-ubuntu-conf
            imagePullPolicy: Always
            volumeMounts:
            - name: local-packages
              mountPath: "/mirror"
          restartPolicy: OnFailure
          priorityClassName: debmirror-high-priority
  concurrencyPolicy: Forbid
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-debmirror-cron-debian
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: local-packages
            persistentVolumeClaim:
              claimName: packages-debian
          containers:
          - name: debian
            image: iainlane/debmirror-debian
            command:
              - /bin/sleep
              - infinity
            envFrom:
            - configMapRef:
                name: debmirror-debian-conf
            imagePullPolicy: Always
            volumeMounts:
            - name: local-packages
              mountPath: "/mirror"
          restartPolicy: OnFailure
          priorityClassName: debmirror-high-priority
  concurrencyPolicy: Forbid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: debmirror-nginx
  name: debmirror-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debmirror-nginx
  template:
    metadata:
      labels:
        app: debmirror-nginx
    spec:
      volumes:
      - name: nginx-index-html
        configMap:
          name: packages-index-html
      - name: nginx-default-conf
        configMap:
          name: nginx-default-conf
      - name: packages-debian
        persistentVolumeClaim:
          claimName: packages-debian
      - name: packages-ubuntu
        persistentVolumeClaim:
          claimName: packages-ubuntu
      - name: packages-ubuntu-ports
        persistentVolumeClaim:
          claimName: packages-ubuntu-ports
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: packages-debian
          mountPath: /mirrors/debian
          subPath: debian
          readOnly: true
        - name: packages-ubuntu
          mountPath: /mirrors/ubuntu
          subPath: ubuntu
          readOnly: true
        - name: packages-ubuntu-ports
          mountPath: /mirrors/ubuntu-ports
          subPath: ubuntu-ports
          readOnly: true
        - name: nginx-default-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx-default.conf
        - name: nginx-index-html
          mountPath: /index.html
          subPath: index.html
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 100m
            memory: 128Mi
      priorityClassName: debmirror-high-priority
